### ISSUE TITLE
Could not find Rails with version X & db/web images NOT_FOUND

### ISSUE THREAD

**Issue by JorgeATR** [Gueils/whales#22]
I followed the usage guide provided in the README to the letter, running the last command block throws off: 
```
Digest: sha256:69e938110f8b915b98e8503d0fae755788d4ab6f37858191ef91f7fb203b1363
Status: Downloaded newer image for icalialabs/belugas:latest
FROM ruby:2.4.0

### ###
### Could not find rails with version 5.1.1
### ###
--------------------------------------------------
version: "2"
---
volumes:
  postgresql-data:
    driver: local
  rails-data:
    driver: local
---
services:
  db:
    image: NOT_FOUND
  web:
    image: NOT_FOUND
```

I have Rails explicitly stated in my Gemfile as:
`gem 'rails', '~> 5.1.1'`

The weird thing is that running the Ruby Beluga does in fact recognize Rails and it's version:
```
docker run \
  --interactive --tty --rm \
  --volume "$PWD":/code \
  whalesil/belugas-ruby
```
Returns:
```
{
"type":"feature","name":"Ruby","version":"2.4.0","description":"The application uses Ruby code","categories":["Language"],"engines":["belugas","belugas-ruby"]}
{"type":"feature",**"name":"rails","version":"5.1.1"**,"description":"The application uses rails","content":"","categories":["Framework"],"cue_locations":[""],"engines":["belugas","belugas-ruby"]}
{"type":"feature","name":"postgresql","version":"0.18","description":"The application uses postgresql","content":"","categories":["Database"],"cue_locations":[""],"engines":["belugas","belugas-ruby"]
}
```
